### ISSUE TITLE
Broken compatibility with .NetStandart 2.0 

### ISSUE THREAD

**Issue by Gamdolf** [meriturva/Hangfire.PerformContextAccessor#1]
Hello, 

I would like to use your package in a .net core 2.2 application (which is supposed to be doable) but you are using a reference which required at least .net core 3.1 

The identified issue is with the package Microsoft.Extensions.DependencyInjection.Abstractions version 6+

You can find more information here : https://github.com/dotnet/runtime/issues/63744

For reference, you can find the compatibility matrix here : https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0 

Could you let me know if you will provide a version compatible with .net core 2.0+ ?

**Comment by meriturva** [comment]
I think it is doable forcing reference to an older version of Microsoft.Extensions.DependencyInjection.Abstractions. I will check as soon as return to work from vacation.
Thanks

**Comment by Gamdolf** [comment]
Thanks for your answer, we will test it when it will be available

**Comment by meriturva** [comment]
@Gamdolf could you please try pre-release version 1.3.0 published right now:

https://www.nuget.org/packages/Bonura.Hangfire.PerformContextAccessor/1.3.0-beta

Thanks.
Diego

**Comment by Gamdolf** [comment]
Hello,

I will check it tomorrow.

Thanks for your fast reaction
________________________________
De : Diego Bonura ***@***.***>
Envoyé : lundi 31 juillet 2023 18:03
À : meriturva/Hangfire.PerformContextAccessor ***@***.***>
Cc : Gamdolf ***@***.***>; Mention ***@***.***>
Objet : Re: [meriturva/Hangfire.PerformContextAccessor] Broken compatibility with .NetStandart 2.0 (Issue #1)


@Gamdolf<https://github.com/Gamdolf> could you please try pre-release version 1.3.0 published right now:

https://www.nuget.org/packages/Bonura.Hangfire.PerformContextAccessor/1.3.0-beta

Thanks.
Diego

**Comment by Gamdolf** [comment]
Hello, 

It look good in the project and unit test. 

I will let you know if we are experiencing any issue in live context but it should be good. 

Thanks for the update

**Comment by meriturva** [comment]
I will deploy a stable release in a few days!
Thanks!

**Comment by meriturva** [comment]
The stable release is published right now!
